name: skorch
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - joblib=0.14.1
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1f
  - pip=20.0.2
  - python=3.7.7
  - pytorch=1.4.0
  - readline=8.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - tabulate=0.8.3
  - tk=8.6.8
  - tqdm=4.44.1
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11

